markdown: kramdown
exclude:
  - LICENSE

layouts: ./_noita
baseurl: /courses/Summer18/sta104.001-1

noita:
  name: Sta 104 - Data Analysis and Statistical Inference (Summer 2015)
  description: Jekyll theme built with Foundation
  author:
    name: Zach White
    url: https://stat.duke.edu/people/zach-white
    absolute: true
  lang: en
  topbar:
    toggle: Menu
    right:
      - name: Schedule
        url: /
      - name: Info
        url: /info/
      - name: Syllabus
        url: /syllabus/
      - name: Resources
        url: /resources/
      - name: Sakai
        url: https://sakai.duke.edu
        absolute: true
      - name: RStudio
        url: https://vm-manage.oit.duke.edu/containers
        absolute: true
      - name: Links
        url: /links/
      - name: FAQ
        url: /faq/
